AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Alfred Bot, lt a bot handle your to-do lists'
Resources:
  lexorderflowers:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: >-
        Alfred Bot, lt a bot handle your to-do lists
      MemorySize: 128
      Timeout: 10
      Role: !<tag:yaml.org,2002:js/undefined> ''
